before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs-legacy nodejs rsync npm openssh-client
  - npm install -g bower
  - bower install --allow-root
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec middleman build --verbose

stages:
  - build
  - deploy

testing:
  script:
    - echo "Build Success."
  stage: build
  except:
    - master

production:
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -av --delete-after build/ deploy@vps.kpmullin.com:public/
  stage: deploy
  only:
    - master
