before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs-legacy nodejs rsync npm openssh-client
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - npm install -g bower
  - bower install --allow-root
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec middleman build --verbose


stages:
  - deploy

make_build:
  script:
    - rsync -avP build/ deploy@vps.kpmullin.com:public/
  stage: deploy
